### PR TITLE
Fix #524 - handle nulls

### LINKED ISSUE #524: EntityVersion.version json translation is wrong
Don't translate if null. fromJson(toJson()) results in "null" not null.

### PR DESCRIPTION
**Pull request by bserdar**

### CODE REVIEW

File: core-api/src/main/java/com/redhat/lightblue/Request.java [hunk 1]
```diff
@@ -93,7 +94,8 @@ public void shallowCopyFrom(Request r) {
     public JsonNode toJson() {
         ObjectNode node = getFactory().objectNode();
         node.put("entity", entityVersion.getEntity());
-        node.put("entityVersion", entityVersion.getVersion());
+        if(entityVersion.getVersion()!=null)
```
Comment (BVulaj) [inline core-api/src/main/java/com/redhat/lightblue/Request.java]: Are we worried about entityVersion being null or entityVersion.version?
