### PR TITLE
Fixes #376 : NPE when performing find on entity with hook

### LINKED ISSUE #376: Bug when performing find on entity with hook
After fixing https://github.com/lightblue-platform/lightblue-audit-hook/issues/28, I am now getting this exception from data nodes when I execute a find against the entity.

```
2015-04-17 10:35:03,962 [hystrix-FindCommand-10] ERROR [com.redhat.lightblue.crud.mongo.MongoCRUDController] null: java.lang.NullPointerException
	at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:198)
	at com.redhat.lightblue.hooks.HookManager.queueHooks(HookManager.java:141)
	at com.redhat.lightblue.crud.mongo.MongoCRUDController.find(MongoCRUDController.java:347)
	at com.redhat.lightblue.mediator.SimpleFindImpl.find(SimpleFindImpl.java:52)
	at com.redhat.lightblue.mediator.Mediator.find(Mediator.java:346)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:66)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:36)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by luan-cestari**
The Hook plugin mechanism was lacking some key pieces to work. I created the remaing components and moved some objects to not create a cyclic dependency. Probably we can rename the packages and some classes again in the future to make it more clear.

This is related to issue https://github.com/lightblue-platform/lightblue-core/issues/376 and it needs other PRs to be merged so we can make the whole project stable.

### CODE REVIEW

File: config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java [hunk 1]
```diff
@@ -173,6 +174,8 @@ private synchronized void initializeMetadata() throws IOException, ClassNotFound
             getJsonTranslator().setValidation(EntityInfo.class, cfg.isValidateRequests());
 
             metadata = cfg.createMetadata(datasources, getJSONParser(), this);
+            initializeFactory(); //re enforce the factory initialization
```
Comment (dcrissman) [inline config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java]: Should it use getFactory() instead?

Comment (luan-cestari) [inline config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java]: You mean replace the two lines (the initializeFactory and the hook init lines) to use the getFactory() directly so it may initialize if it is needed, right?
I thought that when I code these lines but I thought it would make the requirements implicit. I even commented to force the attention that the factory is really needed, so any change in the factory init could impact this method.

But if you think it would be better using that single line statement, I can update the PR immediately after you confirm this.

Comment (dcrissman) [inline config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java]: What if we forced the factory to be passed in? The getMetadata method could simply pass in getFactory().

Comment (luan-cestari) [inline config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java]: Changed as you suggested in the newest commit

**Comment by bserdar** [comment]
Please rename CRUDCRUDOperationContextTest
